---
title: "Curriculum Vitae"
author: W. Zane Billings
date: "`r Sys.Date()`"
output:
  pagedown::html_resume:
    # set it to true for a self-contained HTML page but it'll take longer to render
    self_contained: false
# uncomment this line to produce HTML and PDF in RStudio:
#knit: pagedown::chrome_print
---

Aside
================================================================================

Contact Info {#contact}
--------------------------------------------------------------------------------

- <i class="fa fa-envelope"></i> [wesley.billings@uga.edu](mailto:wesley.billings@uga.edu)
- <i class="fa fa-github"></i> [github.com/wzbillings](https://github.com/wzbillings)
- <i class="fa fa-chain"></i> [wz-billings.rbind.io](https://wz-billings.rbind.io)
- For more information, please contact me via email.


Skills {#skills}
--------------------------------------------------------------------------------

- Statistical modeling and data analysis

- Data visualization, and communication of statistical findings

- Proficient in R, including `ggplot2`, `gt`, and `R Markdown`

- Familiar with: LaTeX, HTML, CSS, Python, MATLAB, Git, Tableau, Mathematica

Last updated on `r Sys.Date()`.



Main
================================================================================

Curriculum Vitae {#title}
--------------------------------------------------------------------------------

### W. Zane Billings

I am currently a PhD student working under Andreas Handel at the University of Georgia. Primarily, my interests are in data analytic methods applied to the immunology and epidemiology of influenza, and my current work is on drivers of immune response to the seasonal influenza vaccine at the host level. More broadly, I am interested in the application of statistical methods to public health, especially in relation to viruses and vaccines.


Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

### Ph.D., Epidemiology and Biostatistics

University of Georgia

Athens, Georgia, USA

Ongoing

Adviser: Andreas Handel

### B.S., Biology and Mathematics

Western Carolina University

Cullowhee, North Carolina, USA

2020


Research Experience {data-icon=laptop}
--------------------------------------------------------------------------------

### Graduate Research Assistant

Beijing Institute of Genomics, Chinese Academy of Sciences

Beijing, China

2011 - 2014

- Performed computational biology research towards understanding regulation of alternative splicing in human and mouse transcriptome.
- Found EGFR pathway related mutations, aimed to understand the impacts of cancer mutations on EGFR signaling pathway.

### Bioinformatican

My Health Gene Technology Co., Ltd.

Beijing, China

2015 - 2016

- Investigated how cancer cells spread to other parts of the body at the single cell level.

### Visiting Scientist

University of Alabama at Birmingham

AL, USA

2016 - 2018

- Investigated the role of mitochondria in development of cancer.
- Investigated the evolution of genome architecture and its role in important evolutionary events.
- Detected thrombotic thrombocytopenic purpura related mutations in mutiple patients' blood genome.
  

Professional Experience {data-icon=suitcase}
--------------------------------------------------------------------------------

### Data Scientist, intern

SupStat Inc.

Beijing, China

2014

::: concise
- Taught R language to beginners. 
- Wrote Shiny app demos.
- Converted statistical tutorials from SPSS to R language.
:::

### Bioinformatician

My Health Gene Technology Co., Ltd.

Beijing, China

2015 - 2016

::: concise
- Analyzed whole-exome sequencing data. 
- Wrote analysis pipelines of ChIP-seq, single cell DNA-seq and single cell RNA-seq.
- Studied tumor metastasis and wrote research reports. 
- Also did case studies to identify the genetic defect causing rare disease.
:::


Teaching Experience {data-icon=chalkboard-teacher}
--------------------------------------------------------------------------------

### Introduction to R Language for Beginners.

Instructor of R and Data Mining Training Courses at SupStat Inc.

Beijing, China

2014

### Computational Biology and Bioinformatics.

Teaching assistant of GBS CB2-201 courses at UAB

AL, USA

2016 - 2017


Selected Publications and Posters {data-icon=file}
--------------------------------------------------------------------------------

### Genetic and epigenetic signals are found predictive to the distribution of intra-individual divergence of alternative splicing.

Poster for 2013 International Conference of Genomics

Qingdao, China

2014

**Yu L**, Chen B, Zhang Z.

### ESCRT-0 complex modulates Rbf mutant cell survival by regulating Rhomboid endosomal trafficking and EGFR signaling.

J Cell Sci. 2016 May 15;129(10):2075-84.

N/A

2016 

Sheng Z, **Yu L**, Zhang T, Pei X, Li X, Zhang Z and Du W. 
